2025-09-27 19:53:31,672 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 19:53:31,798 - __main__ - CRITICAL - Evaluation failed: invalid literal for int() with base 10: 'negative'
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 491, in main
    label_map = {int(k): v for k, v in label_map.items()}
                 ^^^^^^
ValueError: invalid literal for int() with base 10: 'negative'
2025-09-27 20:04:26,795 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:04:26,866 - __main__ - CRITICAL - Evaluation failed: invalid literal for int() with base 10: 'negative'
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 512, in main
    label_map = {int(k): v for k, v in label_map.items()}
                 ^^^^^^
ValueError: invalid literal for int() with base 10: 'negative'
2025-09-27 20:06:56,418 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:06:56,493 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:06:56,507 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:06:56,510 - __main__ - INFO - Processed label map: {0: 0, 1: 1, 2: 2}
2025-09-27 20:06:56,512 - __main__ - INFO - Evaluating baseline model: models/baseline_model.pkl
2025-09-27 20:06:56,512 - __main__ - ERROR - Error evaluating baseline model: [Errno 2] No such file or directory: 'models/baseline_model.pkl'
2025-09-27 20:06:56,590 - __main__ - CRITICAL - Evaluation failed: [Errno 2] No such file or directory: 'models/baseline_model.pkl'
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 518, in main
    results['baseline'] = evaluate_baseline_model(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 145, in evaluate_baseline_model
    model = joblib.load(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models/baseline_model.pkl'
2025-09-27 20:11:07,617 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:11:07,771 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:11:07,840 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:11:07,893 - __main__ - INFO - Processed label map: {0: 0, 1: 1, 2: 2}
2025-09-27 20:11:07,909 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model_20250927_193227.pkl
2025-09-27 20:11:16,976 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-27 20:11:17,555 - __main__ - ERROR - Error calculating metrics: unsupported format string passed to dict.__format__
2025-09-27 20:11:17,716 - __main__ - ERROR - Error evaluating baseline model: unsupported format string passed to dict.__format__
2025-09-27 20:11:17,859 - __main__ - CRITICAL - Evaluation failed: unsupported format string passed to dict.__format__
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 518, in main
    results['baseline'] = evaluate_baseline_model(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 156, in evaluate_baseline_model
    metrics = calculate_metrics(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 401, in calculate_metrics
    print(f"Precision: {precision:.4f}")
                       ^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to dict.__format__
2025-09-27 20:21:55,917 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:21:55,951 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:21:55,953 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:21:55,953 - __main__ - INFO - Processed label map: {0: 'negative', 1: 'neutral', 2: 'positive'}
2025-09-27 20:21:55,954 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model_20250927_193227.pkl
2025-09-27 20:21:58,199 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-27 20:21:58,308 - __main__ - INFO - Evaluating LSTM model: models/lstm_model.keras
2025-09-27 20:21:59,645 - __main__ - ERROR - Error evaluating LSTM model: 34
2025-09-27 20:21:59,657 - __main__ - CRITICAL - Evaluation failed: 34
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 558, in main
    results['lstm'] = evaluate_lstm_model(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 198, in evaluate_lstm_model
    tokenizer = joblib.load(tokenizer_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\pickle.py", line 1255, in load
    dispatch[key[0]](self)
    ~~~~~~~~^^^^^^^^
KeyError: 34
2025-09-27 20:30:14,201 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:30:14,223 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:30:14,232 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:30:14,232 - __main__ - INFO - Processed label map: {0: 'negative', 1: 'neutral', 2: 'positive'}
2025-09-27 20:30:14,232 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model.pkl
2025-09-27 20:30:17,164 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-27 20:30:17,202 - __main__ - INFO - Evaluating LSTM model: models/lstm_model.keras
2025-09-27 20:30:18,224 - __main__ - ERROR - Error evaluating LSTM model: 'str' object has no attribute 'get'
2025-09-27 20:30:18,226 - __main__ - CRITICAL - Evaluation failed: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 563, in main
    results['lstm'] = evaluate_lstm_model(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 203, in evaluate_lstm_model
    tokenizer = tf.keras.preprocessing.text.tokenizer_from_json(tokenizer_json)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\legacy\preprocessing\text.py", line 319, in tokenizer_from_json
    config = tokenizer_config.get("config")
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-09-27 20:36:32,581 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:36:32,594 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:36:32,594 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:36:32,597 - __main__ - INFO - Processed label map: {0: 'negative', 1: 'neutral', 2: 'positive'}
2025-09-27 20:36:32,597 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model.pkl
2025-09-27 20:36:34,162 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-27 20:36:34,436 - __main__ - INFO - Evaluating LSTM model: models/lstm_model.keras
2025-09-27 20:36:35,627 - __main__ - INFO - Loading tokenizer from: models/tokenizer.json
2025-09-27 20:36:35,652 - __main__ - ERROR - Error loading tokenizer: 'str' object has no attribute 'get'
2025-09-27 20:36:35,715 - __main__ - ERROR - Tokenizer file content (first 200 chars): "{\"class_name\": \"Tokenizer\", \"config\": {\"num_words\": 20000, \"filters\": \"!\\\"#$%&()*+,-./:;<=>?@[\\\\]^_`{|}~\\t\\n\", \"lower\": true, \"split\": \" \", \"char_level\": false, \"oov_token\
2025-09-27 20:36:35,773 - __main__ - ERROR - Error evaluating LSTM model: 'str' object has no attribute 'get'
2025-09-27 20:36:35,849 - __main__ - CRITICAL - Evaluation failed: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 580, in main
    results['lstm'] = evaluate_lstm_model(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 211, in evaluate_lstm_model
    tokenizer = tf.keras.preprocessing.text.tokenizer_from_json(tokenizer_json)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\legacy\preprocessing\text.py", line 319, in tokenizer_from_json
    config = tokenizer_config.get("config")
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-09-27 20:40:30,851 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:40:30,890 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:40:30,907 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:40:30,929 - __main__ - INFO - Processed label map: {0: 'negative', 1: 'neutral', 2: 'positive'}
2025-09-27 20:40:30,965 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model.pkl
2025-09-27 20:40:33,204 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-27 20:40:33,211 - __main__ - INFO - Evaluating LSTM model: models/lstm_model.keras
2025-09-27 20:40:34,083 - __main__ - ERROR - Error evaluating LSTM model: 34
2025-09-27 20:40:34,123 - __main__ - CRITICAL - Evaluation failed: 34
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 558, in main
    results['lstm'] = evaluate_lstm_model(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 198, in evaluate_lstm_model
    tokenizer = joblib.load(tokenizer_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\pickle.py", line 1255, in load
    dispatch[key[0]](self)
    ~~~~~~~~^^^^^^^^
KeyError: 34
2025-09-27 20:43:29,313 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-27 20:43:29,327 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-27 20:43:29,328 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-27 20:43:29,330 - __main__ - INFO - Processed label map: {0: 'negative', 1: 'neutral', 2: 'positive'}
2025-09-27 20:43:29,333 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model.pkl
2025-09-27 20:43:31,362 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-27 20:43:31,368 - __main__ - INFO - Evaluating LSTM model: none
2025-09-27 20:43:31,370 - __main__ - ERROR - Error evaluating LSTM model: File format not supported: filepath=none. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(none, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
2025-09-27 20:43:31,375 - __main__ - CRITICAL - Evaluation failed: File format not supported: filepath=none. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(none, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 558, in main
    results['lstm'] = evaluate_lstm_model(
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\Desktop\projects_only\SentimentAnalysis\src\evaluate.py", line 197, in evaluate_lstm_model
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_api.py", line 206, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=none. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(none, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
2025-09-28 14:20:55,137 - __main__ - INFO - Loading evaluation data from data/processed/cleaned.csv
2025-09-28 14:20:55,262 - __main__ - INFO - Loading label mapping from data/processed\label_mapping.json
2025-09-28 14:20:55,270 - __main__ - INFO - Original label map: {'negative': 0, 'neutral': 1, 'positive': 2}
2025-09-28 14:20:55,271 - __main__ - INFO - Processed label map: {0: 'negative', 1: 'neutral', 2: 'positive'}
2025-09-28 14:20:55,272 - __main__ - INFO - Evaluating baseline model: models/baseline/sentiment_baseline_model.pkl
2025-09-28 14:20:59,268 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\baseline_evaluation_metrics.json
2025-09-28 14:20:59,271 - __main__ - INFO - Evaluating LSTM model: models/lstm_model.keras
2025-09-28 14:21:11,405 - __main__ - INFO - Evaluation complete. Metrics saved to evaluation_results\lstm_evaluation_metrics.json
2025-09-28 14:21:11,438 - __main__ - INFO - Combined evaluation results saved to evaluation_results\combined_evaluation_results.json
